CREATE TABLE Language
(
  `SK_Language` INTEGER NOT NULL PRIMARY KEY
  , `ISO639-3Code` CHARACTER(3) NOT NULL
  , `ISO639-2BCode` CHARACTER(3) NULL
  , `ISO639-2TCode` CHARACTER(3) NULL
  , `ISO639-1Code` CHARACTER(2) NULL 
  , `LanguageName` CHARACTER VARYING(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci  NOT NULL
  , `Scope` CHARACTER VARYING(50)  CHARACTER SET utf8 COLLATE utf8_unicode_ci  NOT NULL
  , `Type` CHARACTER VARYING(50)  CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL
  , `MacroLanguageISO639-3Code` CHARACTER(3) NOT NULL
  , `MacrolanguageName` CHARACTER VARYING(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci  NOT NULL
  , `IsChild` TINYINT NOT NULL
);

/* Add path to your local CSV below */
LOAD DATA INFILE '/tmp/Language.csv' INTO TABLE Language CHARACTER SET utf8
FIELDS TERMINATED BY '|' ENCLOSED BY '"' IGNORE 1 LINES 
